---
title: "Evaluation of running time for NW Algorithm"
author: "Aimee Barciauskas"
date: "May 14, 2016"
output: pdf_document
---

```{r, echo = FALSE}
# Credit: http://www.magesblog.com/2013/04/how-to-change-alpha-value-of-colours-in.html
add.alpha <- function(col, alpha=1){
  if(missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb)/255, 2, 
        function(x) 
          rgb(x[1], x[2], x[3], alpha=alpha))  
}
```

Original Data:

```{r}
setwd('~/IdeaProjects/gaceta/')
data <- read.csv('nw_split_norm_times_orig.csv', header = FALSE)
colnames(data) <- c('filename', 'bytes', 'processing_time')

plot(data$bytes, data$processing_time,
     col = add.alpha("orange", alpha=0.2),
     pch = 19)
```


Logged data:

```{r}
data$log_bytes = log(data$bytes)
data$log_time = log(data$processing_time)
data$log_bytes_sq = data$log_bytes**2
data$log_bytes_cub = data$log_bytes**3
plot(data$log_bytes, data$log_time,
     col = add.alpha("steelblue", alpha=0.2),
     pch = 19)#,
     #xlim = c(0,max(data$log_bytes)))


fit <- lm(log_time ~ log_bytes + log_bytes_sq + log_bytes_cub, data = data)
summary(fit)
coeff0 <- as.numeric(fit$coefficients[1])
coeff1 <- as.numeric(fit$coefficients[2])
coeff2 <- as.numeric(fit$coefficients[3])
coeff3 <- as.numeric(fit$coefficients[4])
library(ggplot2)
p1 <- ggplot(data, aes(x=log_bytes, y = log_time, color = "grey")) +
  geom_point() + 
  theme(legend.position='none', panel.background = element_blank()) +
  geom_line(aes(y=fitted.values(fit)), color='orange')
p1

# sanity check
summary(exp(coeff0 + coeff1*data$log_bytes + coeff2*data$log_bytes_sq + coeff3*data$log_bytes_cub))
summary(data$processing_time)

# total run time for all of split_norm
total_size <- 1.98e+8
ms <- exp(coeff0 + coeff1*log(total_size) +
            coeff2*(log(total_size)**2) + 
            coeff3*(log(total_size)**3))
seconds <- ms/1000
minutes <- seconds/60
hours <- minutes/60
hours
# This seems like a vast underestimate

# average size of file in split_norm is 13
avg_file_size <- mean(data$bytes)
num_files <- 13116
average_expected_time_ms <- exp(coeff0 + coeff1*log(avg_file_size) +
                                  coeff2*(log(avg_file_size)**2) +
                                  coeff3*(log(avg_file_size)**3))
total_expected_time_ms <- num_files*average_expected_time_ms
seconds <- total_expected_time_ms/1000
minutes <- seconds/60
hours <- minutes/60
hours
```



